config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root :to => "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	before_create :set_created_at
	before_update :set_updated_at

	def set_created_at
		self.created_at = Time.now
		self.updated_at = Time.now
	end

	def set_updated_at
		self.updated_at = Time.now
	end

	validates_presence_of :body,message: " is required"

	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	before_create :set_created_at
	before_update :set_updated_at

	def set_created_at
		self.created_at = Time.now
		self.updated_at = Time.now
	end

	def set_updated_at
		self.updated_at = Time.now
	end

	validates_presence_of :title,message: " is required"
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :create_comment_struct
	before_action :set_id, only: [:show,:edit,:update,:destroy]

	def index
		@comment_struct.comments = @comment_struct.post.comments
	end

	def new
		@comment_struct.comment = @comment_struct.post.comments.new
	end

	def create
		@comment_struct.comment = @comment_struct.post.comments.new(params_values)
		@comment_struct.comment.author = current_user.id
		if @comment_struct.comment.save
			redirect_to post_comment_path(@comment_struct.post,@comment_struct.comment), notice: "Comment created successfully"
		else
			render :new
		end
	end

	def show		
	end

	def edit		
	end

	def update		
		@comment_struct.comment.assign_attributes(params_values)
		if @comment_struct.comment.save
			redirect_to post_comment_path(@comment_struct.post,@comment_struct.comment), notice: "Comment updated successfully"
		else
			render :edit
		end
	end

	def destroy
		@comment_struct.comment.destroy
		redirect_to post_comments_path(@comment_struct.post), alert: "Comment Deleted"
	end

	private
		def params_values
			params.require(:comment).permit(:body)
		end

		def set_id
			@comment_struct.comment = Comment.find_by_id(params[:id])
		end

		def create_comment_struct
			@comment_struct = CommentStruct.new
			@comment_struct.post = Post.find_by_id(params[:post_id])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_id, only: [:show,:edit,:update,:destroy]	

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params_values)
		@post.created_by = current_user.id
		@post.updated_by = current_user.id
		if @post.save
			redirect_to post_path(@post), notice: "Post created successfully"
		else
			render :new
		end
	end

	def show		
	end

	def edit		
	end

	def update		
		@post.assign_attributes(params_values)
		@post.updated_by = current_user.id
		if @post.save
			redirect_to post_path(@post), notice: "Post updated successfully"
		else
			render :new
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path, alert: "Post Deleted"
	end

	private
		def params_values
			params.require(:post).permit(:title, :body)
		end

		def set_id
			@post = Post.find_by_id(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def set_subheader(arg_header)		
		output = content_tag(:h3,arg_header ,class:"subheader") if arg_header.present?		
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments_table.html.erb
<table  class="table table-striped table-bordered">
	<caption class="fontc">
	<%= "Comments" %>
	<p> </p> </caption>
	<thead>
		<tr>
			<td> <b>Body</b> </td>
			<td> <b>Link</b> </td>
		</tr>
	</thead>
	<% comment_struct.comments.each do |comment| %>
	<tr>
		<td> <%= comment.body %> </td>
		<td> <%= link_to("Show", post_comment_path(comment_struct.post, comment), id: "hyperlink") %> </td>
	</tr>
	<% end %>
</table>

app/views/comments/_form.html.erb
<li class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, cols: 40, rows: 7, class: 'form-control'%>
</li>

app/views/comments/_parent_post_partial.html.erb
<table class="table table-striped table-bordered">
	<caption class="fontc">
	<%= "Post Information" %>
	<p> </p> </caption>
	<thead>
		<tr>
			<td> <b>Title</b> </td>
			<td> <b>Body </b> </td>
		</tr>
	</thead>
	<tr>
		<td> <%= post.title %> </td>
		<td> <%= post.body %> </td>
	</tr>	
</table>

app/views/comments/edit.html.erb
<fieldset>
	<section class="solidbody">
		<legend> <%= set_subheader("Edit Comment") %> </legend><br>
		<%= form_for @comment_struct.comment, url: post_comment_path(@comment_struct.post.id, @comment_struct.comment.id), method: :put do |f| %>
			<%= render "shared/common_error", object_argument: @comment_struct.comment %><br>
			<b>Enter Comment Information</b>
			<p></p>
			<ul>				
				<div class="row">
					<div class="col-md-5">
						<%= render 'form',f: f %>
					</div>
				</div>
			</ul>
			<p>
				<%= link_to 'Cancel', post_comments_path(@comment_struct.post),class: "btn btn-default" %>
				<%= f.submit "Save", class: "btn btn-success" %>
			</p>
		<% end %>			
	</section>
</fieldset>

app/views/comments/index.html.erb
<fieldset>
	<section class="solidbody">
		<legend><%= set_subheader("Comments") %></legend><br>
		<%= render 'parent_post_partial', post: @comment_struct.post %><br>		
		<% if @comment_struct.comments.present? %>				
			<%= render "comments_table", comment_struct: @comment_struct %>
		<%else%>
				<p>
					<h5 class="subheader">No comments to show.</h5>
				</p>					
		<%end%>
		<%= link_to 'Back', posts_path,class: "btn btn-default" %>
		<%= link_to 'New', new_post_comment_path, class: "btn btn-success"%>		
	</section>
</fieldset>

app/views/comments/new.html.erb
<fieldset>
	<section class="solidbody">
		<legend> <%= set_subheader("Enter details for new Comment") %> </legend><br>
		<%= form_for @comment_struct.comment, url: post_comments_path(@comment_struct.post.id) do |f| %>
			<%= render "shared/common_error", object_argument: @comment_struct.comment %><br>
			<b>Enter Comment Information</b>
			<p></p>
			<ul>				
				<div class="row">
					<div class="col-md-5">
						<%= render 'form',f: f %>
					</div>
				</div>
			</ul>
			<p>
				<%= link_to 'Cancel', post_comments_path(@comment_struct.post),class: "btn btn-default" %>
				<%= f.submit "Save", class: "btn btn-success" %>
			</p>
		<% end %>			
	</section>
</fieldset>

app/views/comments/show.html.erb
<fieldset>
    <section class="solidbody">    

    <legend>
        <%= set_subheader("Post Information") %>
    </legend><br>

    <p>
      <b>Body: </b>
      <%= @comment_struct.comment.body %>
    </p>
    <br>

    <%= link_to 'Back', post_comments_path(@comment_struct.post),class: "btn btn-default" %>
    <%= link_to 'Edit', edit_post_comment_path(@comment_struct.post,@comment_struct.comment),class: "btn btn-success" %>
    <%= link_to 'Delete', post_comment_path(@comment_struct.post,@comment_struct.comment), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
    </section>
</fieldset>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>PostsApp</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<%= render 'shared/navbar' %>
	<body>
		<div class="container">
			<% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
			<% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<li class="form-group required">
    <%= f.label :title %>
    <%= f.text_field :title, maxlength: "35" %>
</li>

<li class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, cols: 40, rows: 7, class: 'form-control'%>
</li>

app/views/posts/edit.html.erb
<fieldset>
	<section class="solidbody">
		<legend> <%= set_subheader("Enter details for new Post") %> </legend><br>
		<%= form_for @post do |f| %>
			 <%= render "shared/common_error", object_argument: @post %><br>
   			 <b>Enter Post Information</b>
   			 <p></p>
   			 <ul>				
				<div class="row">
	          		<div class="col-md-5">
						<%= render 'form',f: f %>
					</div>
				</div>
			</ul>
			<p>
		    	<%= link_to 'Cancel', posts_path,class: "btn btn-default" %>
		    	<%= f.submit "Save", class: "btn btn-success" %>
		    </p>
		<% end %>			
	</section>
</fieldset>

app/views/posts/index.html.erb
<fieldset>
	<section class="solidbody">
		<legend><%= set_subheader("Posts") %></legend><br>		
			<% if @posts.present? %>
				
				<table  class="table table-striped table-bordered">
					<tr>
						<td> <b>Title</b> </td>
						<td> <b>Body</b> </td>
						<td> <b>Link</b> </td>
						<td> <b>Comments</b> </td>
					</tr>
					<% @posts.each do |post| %>
					<tr>
						<td> <%= post.title %> </td>
						<td> <%= post.body %> </td>
						<td> <%= link_to("Show", post_path(post), id: "hyperlink") %> </td>
						<td> <%= link_to("Comments", post_comments_path(post), id: "hyperlink") %> </td>
					</tr>
					<% end %>
				</table>
			<%else%>
					<p>
						<h5 class="subheader">No posts to show.</h5>
					</p>					
			<%end%>
			<%= link_to 'New', new_post_path, class: "btn btn-success"%>		
	</section>
</fieldset>

app/views/posts/new.html.erb
<fieldset>
	<section class="solidbody">
		<legend> <%= set_subheader("Enter details for new Post") %> </legend><br>
		<%= form_for @post do |f| %>
			 <%= render "shared/common_error", object_argument: @post %><br>
   			 <b>Enter Post Information</b>
   			 <p></p>
   			 <ul>				
				<div class="row">
	          		<div class="col-md-5">
						<%= render 'form',f: f %>
					</div>
				</div>
			</ul>
			<p>
		    	<%= link_to 'Cancel', posts_path,class: "btn btn-default" %>
		    	<%= f.submit "Save", class: "btn btn-success" %>
		    </p>
		<% end %>			
	</section>
</fieldset>

app/views/posts/show.html.erb
<fieldset>
    <section class="solidbody">    

    <legend>
        <%= set_subheader("Post Information") %>
    </legend><br>

     <p>
      <b>Title: </b>

      <%= @post.title %>
    </p>

    <p>
      <b>Body: </b>
      <%= @post.body %>
    </p>
    <br>

    <%= link_to 'Back', posts_path,class: "btn btn-default" %>
    <%= link_to 'Edit', edit_post_path(@post),class: "btn btn-success" %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
    </section>
</fieldset>

app/views/shared/_common_error.html.erb


<% if object_argument.present? && object_argument.errors.any? %>
    <div id="error_explanation">

        <%if object_argument.errors.count == 1%>
          <h4><span class="glyphicon glyphicon-alert"></span>  Please correct the following error</h4>
        <%else%>
          <h4><span class="glyphicon glyphicon-alert icon-alert"></span>  Please correct the following <%= pluralize(object_argument.errors.count, "error") %> </h4>
        <%end%>
        <ul>
          <% object_argument.errors.full_messages.each do |msg| %>
            <li class="form-group"><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
      	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  	  <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>